### ISSUE TITLE
save activites from dev on heroku not saving

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/alliance-community#27]

**Comment by hectron** [comment]
What seems to be the issue with this?

**Comment by kdflint** [comment]
I don't think it's a bug... I just don't think I have the configuration right yet somehow.

**Comment by hectron** [comment]
So I encountered an error talking with GitHub. What I needed to do is
ensure that the webhook was correctly configured. In my local development
environment, I needed to install ngrok <https://ngrok.com/> to open a port
for the GitHub WebHook to work. NOTE: the ngrok URL will change every time
you restart ngrok.

Cheers,
h

**Comment by kdflint** [comment]
**ASK: Can anyone reproduce this in their local install?**

My major symptom here is that when I try to update the Estimate field in a backlog item, it doesn't update.

I can tell from tailing server log that a request is issued

2015-10-08T15:43:45.917628+00:00 heroku[router]: at=info method=POST path="/alliance/backlog/" host=alliance-dev.herokuapp.com request_id=5192d997-ca0a-4262-81f4-8811f8bcbfb2 fwd="73.209.127.17" dyno=web.1 connect=0ms service=15ms status=404 bytes=2680

However, if I navigate out to Home and back in to the backlog list, my Estimate is not there. (Same is true for all the other form updates related to a backlog.)

Database connection is working because the backlog list itself is getting fetched. Also, when I update data manually, it reflects in the output.

Application log seems to be silent.

**Comment by kdflint** [comment]
To see the heroku installation, go to:

https://alliance-dev.herokuapp.com/alliance/apps/backlog/

Log in as `kdflint` / `password0`

Click on "List backlog..."

Try to update the Estimate field on the one backlog item.

**Comment by goiaba** [comment]
Hi,

I guess the problem is here (yellow):

function updateEstimate(form) { var data = $(form).serializeArray();
data.push({ name: 'action-update-estimate', value: true }); var posting =
$.post("/alliance/backlog/", $.param(data)); posting.done(function (data) {
if (data.success) { backlog_id =
$("#id_estimate-backlog_id").attr('value'); updateDttm(backlog_id,
data.update_dttm); showMessage("Estimate successfuly updated."); } else
showErrors(data.errors); }); posting.fail(function (xhr) { if (xhr.status
== '401') { redirectToLogin($(location).attr('pathname')); } }); }

That is why we always learn: hard-coded is ugly! :-) The correct URL is /
alliance/apps/backlog/

Please correct me if I am wrong.

Best,
Bruno.

**Comment by kdflint** [comment]
Works now - thx Bruno!! We will take up hard code pathing in future sprint.
