### ISSUE TITLE
The local installation process is automated to a large extend

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/alliance-community#65]

**Comment by goiaba** [comment]
@kdflint could you please confirm that the deploy using Vagrant is 100% functional? It is not working here (I'm having troubles with mkvirtualenv). As the Vagrant script does not check if mkvirtualenv returned successfully, pip is installing the requirements globally, instead of in the virtualenv (that actually was not created). These errors appears in the provisioning output:

    ==> default: ================================================================================
    ==> default: Creating a virtualenv and installing requirements!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ==> default: ================================================================================
    ==> default: /tmp/vagrant-shell: line 23: mkvirtualenv: command not found
    ==> default: /tmp/vagrant-shell: line 24: workon: command not found

**Comment by kdflint** [comment]
@goiaba we know the Vagrant install is not fully functional yet. @martsberger was working on it last.

Would be delighted if we could get this completed before get more people on the project!
